### ISSUE TITLE
Typo in the URL on crates.io

### ISSUE THREAD

**Issue by Synthar** [openai-rs/openai-api#2]
Hello, 
I just noticed that there is a typo on crates.io pointing to your github project: "https://github.com/openai-rs/opena**_p_**i-api" 
so it gives a 404 error. 
Hope it helps :)
thanks a lot for the rust crate

**Comment by jiguantong** [comment]
> Hello, I just noticed that there is a typo on crates.io pointing to your github project: "https://github.com/openai-rs/opena**_p_**i-api" so it gives a 404 error. Hope it helps :) thanks a lot for the rust crate

Thanks for the info! Let me correct it.
